version: '3'
services:
  app:
    hostname: yolo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Mapeia a porta do host para a porta do contêiner
    volumes:
      - /srv/volumes/yolo/app/img/_data:/app/img/  # Mapeia o arquivo de entrada para dentro do contêiner
