version: '3'
services:
  app:
    hostname: yolo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Mapeia a porta do host para a porta do contêiner
    devices:
      - "/dev/rtc:/dev/rtc:ro" # DATE
    volumes:
      - "/etc/localtime:/etc/localtime:ro"  # DATE
      # - shared-data:/app/img/
      # - /srv/volumes/system-monitora-yolo/app/img/_data:/app/img/  # Mapeia o arquivo de entrada para dentro do contêiner
      - /srv/volumes/system-monitora-script/yolo/_data:/app/img/  # Mapeia o arquivo de entrada para dentro do contêiner


# volumes:
#   shared-data: